
services:
  web:
    build: .

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

  qdrant:
    image: qdrant/qdrant

    ports: 
      - "6333:6333"

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
